#!/usr/bin/env python3.2
import sys
import os
import subprocess
from urllib.request import urlopen

toolsdir = os.environ.get('NATIVE_TOOLS')
toolsurl = os.environ.get('NATIVE_TOOLS_URL')
# make sure we can proceed
if toolsdir == None:
    print("No NATIVE_TOOLS in environment. Exiting")
    sys.exit(1)

# find the package .zip
pkgname = sys.argv[1]
pkgpath = False
if os.path.isfile(pkgname):
    pkgpath = os.path.abspath(pkgname)

if not pkgpath:
    print('No package ' + pkgname + ' found. Exiting')
    sys.exit(1)

# cd to the toolsdir 
print('Unpacking ' + pkgpath + ' into ' + toolsdir)
os.chdir(toolsdir)
subprocess.call(['unzip', '-uo', pkgpath])
print('Done')
    
#url = sys.argv[1]
#fname = url.split('/')[-1]
#f = open(fname, 'wb')
#f.write(urlopen(url).read())
#f.close()

