PATH="$HOME/bin:$PATH"
MANPATH="$HOME/man:$MANPATH"
LD_LIBRARY_PATH="$HOME/lib:$LD_LIBRARY_PATH"
MAKEFLAGS="-I$HOME/include"

export PATH MANPATH LD_LIBRARY_PATH MAKEFLAGS

QNX_TARGET="$HOME/target/qnx6"
QNX_HOST="$HOME"
QNX_CONFIGURATION="$HOME/etc/qnxconf"
MAKEFLAGS="-I$QNX_TARGET/usr/include"
LD_LIBRARY_PATH="$HOME/usr/lib:$LD_LIBRARY_PATH"
PATH="$QNX_HOST/usr/bin:$PATH"

export QNX_TARGET QNX_HOST QNX_CONFIGURATION MAKEFLAGS LD_LIBRARY_PATH PATH
