--- nbsdgames.orig/Makefile	2021-04-28 12:29:34.026689292 +0200
+++ nbsdgames/Makefile	2021-04-28 12:54:33.800243197 +0200
@@ -1,7 +1,7 @@
 # -*- Makefile -*-
 ifndef $(CFLAGS)
-	CFLAGS= -O3 -lncurses -Wno-unused-result
-	#-O3 --std=c99 -lcurses -DNO_MOUSE for NetBSD curses
+	CFLAGS= -O3 -lncurses -Wno-unused-result -std=c99
+	#-O3 --std=c99 -lncurses -DNO_MOUSE for NetBSD curses
 	#adding --std=c99 makes warnings in GNU, and the blame is upon glibc feature test macros. my code is correct.
 endif
 ifndef $(GAMES_DIR)
@@ -10,7 +10,7 @@
 ifndef $(SCORES_DIR)
 	SCORES_DIR=/usr/games
 endif
-all: jewels sudoku mines reversi checkers battleship rabbithole sos pipes fifteen memoblocks fisher muncher miketron redsquare darrt snakeduel
+all: jewels sudoku mines reversi checkers battleship rabbithole sos pipes fifteen memoblocks fisher muncher miketron redsquare snakeduel
 scorefiles:
 	touch $(SCORES_DIR)/pp_scores
 	touch $(SCORES_DIR)/jw_scores
--- nbsdgames.orig/Makefile	2021-05-07 10:09:53.609810033 +0200
+++ nbsdgames/Makefile	2021-05-07 10:11:07.022869225 +0200
@@ -64,6 +64,6 @@
 	rm ./jewels ./sudoku ./checkers ./mines ./reversi ./battleship ./rabbithole ./sos ./pipes ./fifteen ./memoblocks ./fisher ./muncher ./miketron ./redsquare ./darrt ./snakeduel
 uninstall:
 	rm $(GAMES_DIR)/jewels $(GAMES_DIR)/sudoku $(GAMES_DIR)/checkers $(GAMES_DIR)/mines $(GAMES_DIR)/reversi $(GAMES_DIR)/battleship $(GAMES_DIR)/rabbithole $(GAMES_DIR)/sos $(GAMES_DIR)/pipes $(GAMES_DIR)/fifteen $(GAMES_DIR)/memoblocks $(GAMES_DIR)/fisher $(GAMES_DIR)/muncher $(GAMES_DIR)/miketron $(GAMES_DIR)/redsquare $(GAMES_DIR)/darrt $(GAMES_DIR)/snakeduel
-install: scorefiles jewels sudoku mines reversi checkers battleship rabbithole sos pipes fifteen memoblocks fisher muncher miketron redsquare darrt snakeduel
-	cp jewels sudoku mines reversi checkers battleship rabbithole sos pipes fifteen memoblocks fisher muncher miketron redsquare darrt snakeduel $(GAMES_DIR)
+install: scorefiles jewels sudoku mines reversi checkers battleship rabbithole sos pipes fifteen memoblocks fisher muncher miketron redsquare snakeduel
+	cp jewels sudoku mines reversi checkers battleship rabbithole sos pipes fifteen memoblocks fisher muncher miketron redsquare snakeduel $(GAMES_DIR)
 
