find /Users/testuser/BB/src/playbook-dev-tools/work/tgl/ -type f | xargs grep -l execinfo
work/tgl/config.h.in
work/tgl/config.log
work/tgl/configure
work/tgl/configure.ac
work/tgl/main.c
work/tgl/README.es
work/tgl/README.md
work/tgl/tgl/config.h.in
work/tgl/tgl/configure
work/tgl/tgl/configure.ac
work/tgl/tgl/generate.c
work/tgl/tgl/tl-parser/tlc.c
