--- Makefile.orig	2010-09-10 16:46:02.000000000 -0600
+++ Makefile	2012-06-28 11:09:34.000000000 -0600
@@ -15,9 +15,9 @@
 SHELL=/bin/sh
 
 # To assist in cross-compiling
-CC=gcc
-AR=ar
-RANLIB=ranlib
+CC=arm-unknown-nto-qnx6.5.0eabi-gcc
+AR=arm-unknown-nto-qnx6.5.0-ar
+RANLIB=arm-unknown-nto-qnx6.5.0eabi-ranlib
 LDFLAGS=
 
 BIGFILES=-D_FILE_OFFSET_BITS=64
@@ -35,7 +35,7 @@
       decompress.o \
       bzlib.o
 
-all: libbz2.a bzip2 bzip2recover test
+all: libbz2.a bzip2 bzip2recover
 
 bzip2: libbz2.a bzip2.o
 	$(CC) $(CFLAGS) $(LDFLAGS) -o bzip2 bzip2.o -L. -lbz2
