set( CMAKE_SYSTEM_NAME QNX )
set( CMAKE_SYSTEM_VERSION 1 )

set( CMAKE_INSTALL_PREFIX "$ENV{PREFIX}" )

set( CMAKE_FIND_ROOT_PATH "${CMAKE_SOURCE_DIR}" "$ENV{QNX_TARGET}" "$ENV{LIBUUID_DIR}" "${CMAKE_INSTALL_PREFIX}" "${CMAKE_INSTALL_PREFIX}/share" )

set( CMAKE_C_COMPILER   "$ENV{PBTARGETARCH}-gcc" )
set( CMAKE_CXX_COMPILER "$ENV{PBTARGETARCH}-g++" )

